machine:
  timezone:
    Asia/Tokyo
dependencies:
  cache_directories:
    - vagrant
    - ~/.vagrant.d
  pre:
    - wget https://dl.bintray.com/mitchellh/vagrant/vagrant_1.6.5_x86_64.deb
    - sudo dpkg -i vagrant_1.6.5_x86_64.deb
    - vagrant plugin install vagrant-aws
test:
  pre:
    - vagrant up prod
  post:
      - vagrant destroy prod --force