version: 2

jobs:
  test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: |
          sudo sh -c "echo \"deb http://download.virtualbox.org/virtualbox/debian xenial contrib\" >> /etc/apt/sources.list"
          sudo apt-get update -q
          sudo apt-get install -q linux-headers-$(uname -r) build-essential virtualbox-5.1 dkms --fix-missing
          wget "https://releases.hashicorp.com/vagrant/2.2.3/vagrant_2.2.3_x86_64.deb"
          sudo dpkg -i vagrant_2.2.3_x86_64.deb
      - run: vagrant up prod
      - run: vagrant destroy prod --force

workflows:
  version: 2
  test:
    jobs:
      - test
